model_family: phi

LoRA:
  r: 0 # do not use LoRA for finetuning
  alpha: 32
  dropout: 0.05

data_path: locuslab/TOFU
split: full
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 5
lr: 1e-5
save_dir: ./llm_weights/ft_epoch${num_epochs}_lr${lr}_${model_family}_${split}_wd${weight_decay}

weight_decay: 0.01
seed: 42